[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tinyGPT"
version = "0.0.1"
requires-python = ">=3.9"

dependencies = [
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]